-- Portuguese label translations – measures (batch B, rows 171-340)
-- Source: label2 (English). label3/label4 cleared.
SET NAMES utf8mb4;

UPDATE `measures` SET `label1` = 'Assistência na Resposta a Incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Response Assistance';
UPDATE `measures` SET `label1` = 'Decisões de Controlo de Acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Control Decisions';
UPDATE `measures` SET `label1` = 'Comité de Integridade dos Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data Integrity Board';
UPDATE `measures` SET `label1` = 'Segurança do Pessoal Externo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'External Personnel Security';
UPDATE `measures` SET `label1` = 'É detetado código móvel não autorizado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Unauthorized mobile code is detected';
UPDATE `measures` SET `label1` = 'Instalação de software em sistemas operacionais', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Installation of software on operational systems';
UPDATE `measures` SET `label1` = 'Os sistemas de informação externos estão catalogados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'External information systems are catalogued';
UPDATE `measures` SET `label1` = 'Confidencialidade e Integridade na Transmissão', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Transmission Confidentiality and Integrity';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Autorização de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Authorization Policy and Procedures';
UPDATE `measures` SET `label1` = 'Gestão Centralizada', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Central Management';
UPDATE `measures` SET `label1` = 'Recuperação e Reconstituição do Sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Recovery and Reconstitution';
UPDATE `measures` SET `label1` = 'Desidentificação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'De-Identification';
UPDATE `measures` SET `label1` = 'Cópia de Segurança do Sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Backup';
UPDATE `measures` SET `label1` = 'Iluminação de Emergência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Emergency Lighting';
UPDATE `measures` SET `label1` = 'Partilha de Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Sharing';
UPDATE `measures` SET `label1` = 'Acesso Sem Fios', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Wireless Access';
UPDATE `measures` SET `label1` = 'Seleção de Linha de Base', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Baseline Selection';
UPDATE `measures` SET `label1` = 'Local de Armazenamento Alternativo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternate Storage Site';
UPDATE `measures` SET `label1` = 'Capacidade de Armazenamento de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Storage Capacity';
UPDATE `measures` SET `label1` = 'Honeypots', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Honeypots';
UPDATE `measures` SET `label1` = 'Reautenticação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Re-authentication';
UPDATE `measures` SET `label1` = 'Os utilizadores privilegiados compreendem os seus papéis e responsabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privileged users understand roles & responsibilities';
UPDATE `measures` SET `label1` = 'O posicionamento da organização na infraestrutura crítica e no seu setor industrial é identificado e comunicado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The organization''s place in critical infrastructure and its industry sector is identified and communicated';
UPDATE `measures` SET `label1` = 'Proteção contra Danos Causados pela Água', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Water Damage Protection';
UPDATE `measures` SET `label1` = 'Formação Baseada em Funções', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Role-Based Training';
UPDATE `measures` SET `label1` = 'Serviços de Sistemas Externos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'External System Services';
UPDATE `measures` SET `label1` = 'Processo de Desenvolvimento, Normas e Ferramentas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Development Process, Standards, and Tools';
UPDATE `measures` SET `label1` = 'Aplicações Independentes da Plataforma', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Platform-Independent Applications';
UPDATE `measures` SET `label1` = 'Os ambientes de desenvolvimento e teste são separados do ambiente de produção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The development and testing environment(s) are separate from the production environment';
UPDATE `measures` SET `label1` = 'Mapeamento do ecossistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Ecosystem mapping';
UPDATE `measures` SET `label1` = 'Estabelecimento e Gestão de Chaves Criptográficas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cryptographic Key Establishment and Management';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Avaliação de Risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk Assessment Policy and Procedures';
UPDATE `measures` SET `label1` = 'Geração de Registos de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Generation';
UPDATE `measures` SET `label1` = 'Acesso Individual', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Individual Access';
UPDATE `measures` SET `label1` = 'Segurança de ativos fora das instalações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security of assets off-premises';
UPDATE `measures` SET `label1` = 'Monitor de Referência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Reference Monitor';
UPDATE `measures` SET `label1` = 'Serviço Seguro de Resolução de Nomes/Endereços (Resolver Recursivo ou com Cache)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure Name / Address Resolution Service (Recursive or Caching Resolver)';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Gestão de Configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration Management Policy and Procedures';
UPDATE `measures` SET `label1` = 'Reporte de Incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Reporting';
UPDATE `measures` SET `label1` = 'Os eventos detetados são analisados para compreender os alvos e métodos de ataque', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detected events are analyzed to understand attack targets and methods';
UPDATE `measures` SET `label1` = 'Desenvolvimento Personalizado de Componentes Críticos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Customized Development of Critical Components';
UPDATE `measures` SET `label1` = 'Privacidade e proteção de DCP', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy and protection of PII';
UPDATE `measures` SET `label1` = 'Redundância das instalações de processamento de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Redundancy of information processing facilities';
UPDATE `measures` SET `label1` = 'As redes de comunicações e de controlo estão protegidas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Communications and control networks are protected';
UPDATE `measures` SET `label1` = 'Direitos de acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access rights';
UPDATE `measures` SET `label1` = 'Segregação de redes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Segregation of networks';
UPDATE `measures` SET `label1` = 'Formação Fornecida pelo Desenvolvedor', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Developer-Provided Training';
UPDATE `measures` SET `label1` = 'Interligações de Sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Interconnections';
UPDATE `measures` SET `label1` = 'As ameaças, vulnerabilidades, probabilidades e impactos são utilizados para determinar o risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Threats, vulnerabilities, likelihoods, and impacts are used to determine risk';
UPDATE `measures` SET `label1` = 'Energia de Emergência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Emergency Power';
UPDATE `measures` SET `label1` = 'A manutenção e reparação de ativos organizacionais é realizada e registada em tempo útil, com ferramentas aprovadas e controladas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Maintenance and repair of organizational assets is performed and logged in a timely manner, with approved and controlled tools';
UPDATE `measures` SET `label1` = 'Registos de atividade (logging)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Logging';
UPDATE `measures` SET `label1` = 'Segregação de funções', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Segregation of duties';
UPDATE `measures` SET `label1` = 'Nós Thin', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Thin Nodes';
UPDATE `measures` SET `label1` = 'Gestão de configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration management';
UPDATE `measures` SET `label1` = 'Existem processos de controlo de alterações de configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration change control processes are in place';
UPDATE `measures` SET `label1` = 'Código Móvel', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Mobile Code';
UPDATE `measures` SET `label1` = 'Princípios de Engenharia de Segurança e Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Engineering Principles';
UPDATE `measures` SET `label1` = 'Marcação de Suportes de Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Marking';
UPDATE `measures` SET `label1` = 'É detetado código malicioso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Malicious code is detected';
UPDATE `measures` SET `label1` = 'Proteção de Ligações Sem Fios', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Wireless Link Protection';
UPDATE `measures` SET `label1` = 'Análise de Canais Encobertos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Covert Channel Analysis';
UPDATE `measures` SET `label1` = 'Deteção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detection';
UPDATE `measures` SET `label1` = 'Triagem de Desenvolvedores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Developer Screening';
UPDATE `measures` SET `label1` = 'Processo de Aquisição', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Acquisition Process';
UPDATE `measures` SET `label1` = 'Reparação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Redress';
UPDATE `measures` SET `label1` = 'Filtragem de tráfego', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Traffic filtering';
UPDATE `measures` SET `label1` = 'Proteção dos sistemas de informação durante testes de auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection of information systems during audit testing';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Resposta a Incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Response Policy and Procedures';
UPDATE `measures` SET `label1` = 'Procedimento de manutenção da segurança informática', `label3` = NULL, `label4` = NULL WHERE `label2` = 'IT security maintenance procedure';
UPDATE `measures` SET `label1` = 'Os requisitos de resiliência para suportar a prestação de serviços críticos estão estabelecidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Resilience requirements to support delivery of critical services are established';
UPDATE `measures` SET `label1` = 'Os papéis e responsabilidades de cibersegurança para toda a força de trabalho e partes interessadas terceiras (ex.: fornecedores, clientes, parceiros) estão estabelecidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cybersecurity roles and responsibilities for the entire workforce and third-party stakeholders (e.g., suppliers, customers, partners) are established';
UPDATE `measures` SET `label1` = 'Gestão de Configuração pelo Desenvolvedor', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Developer Configuration Management';
UPDATE `measures` SET `label1` = 'Disponibilidade de Recursos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Resource Availability';
UPDATE `measures` SET `label1` = 'As relações públicas são geridas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Public relations are managed';
UPDATE `measures` SET `label1` = 'A política de segurança da informação organizacional está estabelecida', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Organizational information security policy is established';
UPDATE `measures` SET `label1` = 'Contacto com autoridades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contact with authorities';
UPDATE `measures` SET `label1` = 'A tolerância ao risco organizacional é determinada e claramente expressa', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Organizational risk tolerance is determined and clearly expressed';
UPDATE `measures` SET `label1` = 'Regras de Comportamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Rules of Behavior';
UPDATE `measures` SET `label1` = 'Os impactos e probabilidades potenciais para o negócio são identificados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Potential business impacts and likelihoods are identified';
UPDATE `measures` SET `label1` = 'Autenticação por Módulo Criptográfico', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cryptographic Module Authentication';
UPDATE `measures` SET `label1` = 'Equipamento de Energia e Cablagem', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Power Equipment and Cabling';
UPDATE `measures` SET `label1` = 'É implementado um Ciclo de Vida de Desenvolvimento de Sistemas para gerir os sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'A System Development Life Cycle to manage systems is implemented';
UPDATE `measures` SET `label1` = 'Indicadores de segurança do sistema de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security indicators';
UPDATE `measures` SET `label1` = 'Informação de teste', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Test information';
UPDATE `measures` SET `label1` = 'O acesso remoto é gerido', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Remote access is managed';
UPDATE `measures` SET `label1` = 'Inventário de Informação Pessoalmente Identificável', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Inventory of Personally Identifiable Information';
UPDATE `measures` SET `label1` = 'Conceito de Operações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Concept of Operations';
UPDATE `measures` SET `label1` = 'Requisitos legais, estatutários, regulamentares e contratuais', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Legal, statutory, regulatory and contractual requirements';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Manutenção do Sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Maintenance Policy and Procedures';
UPDATE `measures` SET `label1` = 'Informação de autenticação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authentication information';
UPDATE `measures` SET `label1` = 'A integridade da rede está protegida, incorporando a segregação de redes quando adequado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Network integrity is protected, incorporating network segregation where appropriate';
UPDATE `measures` SET `label1` = 'Planos de Segurança e Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Plans';
UPDATE `measures` SET `label1` = 'Conteúdo de Acesso Público', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Publicly Accessible Content';
UPDATE `measures` SET `label1` = 'Gestão de Contas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Account Management';
UPDATE `measures` SET `label1` = 'Adaptação da Linha de Base', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Baseline Tailoring';
UPDATE `measures` SET `label1` = 'Requisitos de segurança de aplicações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Application security requirements';
UPDATE `measures` SET `label1` = 'Redução de Registos de Auditoria e Geração de Relatórios', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Reduction and Report Generation';
UPDATE `measures` SET `label1` = 'A manutenção remota de ativos organizacionais é aprovada, registada e realizada de forma a impedir o acesso não autorizado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Remote maintenance of organizational assets is approved, logged, and performed in a manner that prevents unauthorized access';
UPDATE `measures` SET `label1` = 'Termos e condições de emprego', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Terms and conditions of employment';
UPDATE `measures` SET `label1` = 'Estão estabelecidos processos para receber, analisar e responder a vulnerabilidades divulgadas à organização por fontes internas e externas (ex.: testes internos, boletins de segurança ou investigadores de segurança)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Processes are established to receive, analyze and respond to vulnerabilities disclosed to the organization from internal and external sources (e.g. internal testing, security bulletins, or security researchers)';
UPDATE `measures` SET `label1` = 'Remediação de Falhas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Flaw Remediation';
UPDATE `measures` SET `label1` = 'Ocultação e Desinformação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Concealment and Misdirection';
UPDATE `measures` SET `label1` = 'Resposta a incidentes de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response to information security incidents';
UPDATE `measures` SET `label1` = 'Gestão de alterações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Change management';
UPDATE `measures` SET `label1` = 'Gestão da segurança da informação na cadeia de abastecimento de TIC', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Managing information security in the ICT supply chain';
UPDATE `measures` SET `label1` = 'Direitos de acesso privilegiado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privileged access rights';
UPDATE `measures` SET `label1` = 'São utilizados mecanismos de verificação de integridade para verificar a integridade do hardware', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Integrity checking mechanisms are used to verify hardware integrity';
UPDATE `measures` SET `label1` = 'Recursos de Segurança da Informação e Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Security and Privacy Resources';
UPDATE `measures` SET `label1` = 'Avaliação de Risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk Assessment';
UPDATE `measures` SET `label1` = 'Filtragem web', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Web filtering';
UPDATE `measures` SET `label1` = 'Eventos de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Events';
UPDATE `measures` SET `label1` = 'Levantamento de Contramedidas de Vigilância Técnica', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Technical Surveillance Countermeasures Survey';
UPDATE `measures` SET `label1` = 'Restrições de Utilização de Software', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Software Usage Restrictions';
UPDATE `measures` SET `label1` = 'Proteção contra Spam', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Spam Protection';
UPDATE `measures` SET `label1` = 'Funções do Programa de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Program Roles';
UPDATE `measures` SET `label1` = 'Configuração dos sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Systems configuration';
UPDATE `measures` SET `label1` = 'Acreditação de segurança do sistema de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security accreditation';
UPDATE `measures` SET `label1` = 'Restrição de acesso à informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information access restriction';
UPDATE `measures` SET `label1` = 'As permissões de acesso são geridas, incorporando os princípios do menor privilégio e da separação de funções', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access permissions are managed, incorporating the principles of least privilege and separation of duties';
UPDATE `measures` SET `label1` = 'Testes, Formação e Monitorização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Testing, Training, and Monitoring';
UPDATE `measures` SET `label1` = 'Ações Permitidas sem Identificação ou Autenticação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Permitted Actions without Identification or Authentication';
UPDATE `measures` SET `label1` = 'Declaração da Lei de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Act Statement';
UPDATE `measures` SET `label1` = 'O pessoal de segurança física e da informação compreende os seus papéis e responsabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical and information security personnel understand roles & responsibilities';
UPDATE `measures` SET `label1` = 'Manutenção Atempada', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Timely Maintenance';
UPDATE `measures` SET `label1` = 'Utilização de programas utilitários privilegiados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Use of privileged utility programs';
UPDATE `measures` SET `label1` = 'Correlação e análise de registos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Logs correlation and analysis';
UPDATE `measures` SET `label1` = 'Responsabilidades da gestão', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Management responsibilities';
UPDATE `measures` SET `label1` = 'Utilização aceitável da informação e de outros ativos associados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Acceptable use of information and other associated assets';
UPDATE `measures` SET `label1` = 'Arquitetura e Design de Segurança pelo Desenvolvedor', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Developer Security Architecture and Design';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Integridade do Sistema e da Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System and Information Integrity Policy and Procedures';
UPDATE `measures` SET `label1` = 'A determinação da tolerância ao risco da organização é fundamentada pelo seu papel na infraestrutura crítica e pela análise de risco específica do setor', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The organization''s determination of risk tolerance is informed by its role in critical infrastructure and sector specific risk analysis';
UPDATE `measures` SET `label1` = 'Os executivos seniores compreendem os seus papéis e responsabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Senior executives understand roles & responsibilities';
UPDATE `measures` SET `label1` = 'As respostas ao risco são identificadas e priorizadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk responses are identified and prioritized';
UPDATE `measures` SET `label1` = 'Corte de Emergência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Emergency Shutoff';
UPDATE `measures` SET `label1` = 'Testes de segurança no desenvolvimento e aceitação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security testing in development and acceptance';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Identificação e Autenticação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identification and Authentication Policy and Procedures';
UPDATE `measures` SET `label1` = 'Definição da Missão e dos Processos de Negócio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Mission and Business Process Definition';
UPDATE `measures` SET `label1` = 'Programa de Ameaças Internas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Insider Threat Program';
UPDATE `measures` SET `label1` = 'Processo disciplinar', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Disciplinary process';
UPDATE `measures` SET `label1` = 'A rede é monitorizada para detetar potenciais eventos de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The network is monitored to detect potential cybersecurity events';
UPDATE `measures` SET `label1` = 'Políticas e Procedimentos de Avaliação, Autorização e Monitorização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Assessment, Authorization, and Monitoring Policies and Procedures';
UPDATE `measures` SET `label1` = 'Comité de Gestão de Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data Management Board';
UPDATE `measures` SET `label1` = 'Manutenção Controlada', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Controlled Maintenance';
UPDATE `measures` SET `label1` = 'Programa de Consciencialização sobre Ameaças', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Threat Awareness Program';
UPDATE `measures` SET `label1` = 'Controlos de Temperatura e Humidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Temperature and Humidity Controls';
UPDATE `measures` SET `label1` = 'Gestão do Risco da Cadeia de Abastecimento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Supply Chain Risk Management';
UPDATE `measures` SET `label1` = 'Proteção de Memória', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Memory Protection';
UPDATE `measures` SET `label1` = 'Análise de Vulnerabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Vulnerability Scanning';
UPDATE `measures` SET `label1` = 'Triagem', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Screening';
UPDATE `measures` SET `label1` = 'Proteção de registos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection of records';
UPDATE `measures` SET `label1` = 'Contas de administração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Administration accounts';
UPDATE `measures` SET `label1` = 'Notificação de Início de Sessão Anterior', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Previous Logon (Access) Notification';
UPDATE `measures` SET `label1` = 'Segurança da informação durante perturbações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security during disruption';
UPDATE `measures` SET `label1` = 'Registos de Formação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Training Records';
UPDATE `measures` SET `label1` = 'Voz sobre Protocolo de Internet', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Voice Over Internet Protocol';
UPDATE `measures` SET `label1` = 'Proteção da Informação em Repouso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection of Information At Rest';
UPDATE `measures` SET `label1` = 'Falha em Estado Conhecido', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Fail in Known State';
UPDATE `measures` SET `label1` = 'Localização e proteção de equipamentos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Equipment siting and protection';
UPDATE `measures` SET `label1` = 'Formação em Contingência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contingency Training';
UPDATE `measures` SET `label1` = 'Segregação de sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System segregation';
UPDATE `measures` SET `label1` = 'Gestão da Qualidade dos Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data Quality Management';
UPDATE `measures` SET `label1` = 'Proteção de Fronteiras', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Boundary Protection';
UPDATE `measures` SET `label1` = 'Análise de Criticidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Criticality Analysis';
UPDATE `measures` SET `label1` = 'Relatórios de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Reporting';
UPDATE `measures` SET `label1` = 'As identidades e credenciais são geridas para dispositivos e utilizadores autorizados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identities and credentials are managed for authorized devices and users';
UPDATE `measures` SET `label1` = 'Equipa Integrada de Análise de Segurança da Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Integrated Information Security Analysis Team';
UPDATE `measures` SET `label1` = 'Manutenção Não Local', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Nonlocal Maintenance';
UPDATE `measures` SET `label1` = 'A atividade do pessoal é monitorizada para detetar potenciais eventos de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel activity is monitored to detect potential cybersecurity events';
UPDATE `measures` SET `label1` = 'O planeamento e os testes de resposta e recuperação são realizados com fornecedores e prestadores de serviços terceiros', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response and recovery planning and testing are conducted with suppliers and third-party providers';
