-- Portuguese label translations – measures (batch C, rows 341-507)
-- Source: label2 (English). label3/label4 cleared.
SET NAMES utf8mb4;

UPDATE `measures` SET `label1` = 'Plano do Programa de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Program Plan';
UPDATE `measures` SET `label1` = 'Arquitetura e Aprovisionamento para Serviço de Resolução de Nomes/Endereços', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Architecture and Provisioning for Name / Address Resolution Service';
UPDATE `measures` SET `label1` = 'A eficácia das tecnologias de proteção é partilhada com as partes adequadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Effectiveness of protection technologies is shared with appropriate parties';
UPDATE `measures` SET `label1` = 'Políticas de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Policies for information security';
UPDATE `measures` SET `label1` = 'Os ativos são geridos formalmente ao longo da sua remoção, transferência e eliminação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Assets are formally managed throughout removal, transfers, and disposition';
UPDATE `measures` SET `label1` = 'Os processos de deteção são continuamente melhorados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detection processes are continuously improved';
UPDATE `measures` SET `label1` = 'Local de Trabalho Alternativo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternate Work Site';
UPDATE `measures` SET `label1` = 'Conteúdo dos Registos de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Content of Audit Records';
UPDATE `measures` SET `label1` = 'Eliminação de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information deletion';
UPDATE `measures` SET `label1` = 'Proteção da Informação de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection of Audit Information';
UPDATE `measures` SET `label1` = 'Saneamento de Suportes de Armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Sanitization';
UPDATE `measures` SET `label1` = 'Os fluxos de comunicação e dados organizacionais estão mapeados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Organizational communication and data flows are mapped';
UPDATE `measures` SET `label1` = 'O plano de resposta é executado durante ou após um evento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response plan is executed during or after an event';
UPDATE `measures` SET `label1` = 'Gestão da continuidade de negócio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Business continuity management';
UPDATE `measures` SET `label1` = 'Gestão de vulnerabilidades técnicas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Management of technical vulnerabilities';
UPDATE `measures` SET `label1` = 'Proteção contra Pulso Eletromagnético', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Electromagnetic Pulse Protection';
UPDATE `measures` SET `label1` = 'Componentes de Sistema sem Suporte', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Unsupported System Components';
UPDATE `measures` SET `label1` = 'Recursos Humanos de Segurança e Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Workforce';
UPDATE `measures` SET `label1` = 'Registos de Acesso de Visitantes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Visitor Access Records';
UPDATE `measures` SET `label1` = 'Validação de Dados de Entrada', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Input Validation';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Participação Individual', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Individual Participation Policy and Procedures';
UPDATE `measures` SET `label1` = 'Integridade de Software, Firmware e Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Software, Firmware, and Information Integrity';
UPDATE `measures` SET `label1` = 'Plano de Gestão de Configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration Management Plan';
UPDATE `measures` SET `label1` = 'Acesso ao código fonte', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access to source code';
UPDATE `measures` SET `label1` = 'Restrições de Utilização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Usage Restrictions';
UPDATE `measures` SET `label1` = 'Desclassificação de Suportes de Armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Downgrading';
UPDATE `measures` SET `label1` = 'Protocolos de Comunicação Alternativos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternate Communications Protocols';
UPDATE `measures` SET `label1` = 'Modo de Segurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Safe Mode';
UPDATE `measures` SET `label1` = 'Identificação e Autenticação (Utilizadores da Organização)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identification and Authentication (Organizational Users)';
UPDATE `measures` SET `label1` = 'Marcas Temporais', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Time Stamps';
UPDATE `measures` SET `label1` = 'Os fornecedores e parceiros terceiros de sistemas de informação, componentes e serviços são identificados, priorizados e avaliados através de um processo de avaliação de risco da cadeia de fornecimento cibernética', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Suppliers and third party partners of information systems, components, and services are identified, prioritized, and assessed using a cyber supply chain risk assessment process';
UPDATE `measures` SET `label1` = 'Atividades de monitorização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Monitoring activities';
UPDATE `measures` SET `label1` = 'Os processos de proteção são continuamente melhorados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection processes are continuously improved';
UPDATE `measures` SET `label1` = 'A partilha voluntária de informação ocorre com partes externas para aumentar a consciencialização situacional de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Voluntary information sharing occurs with external stakeholders to achieve broader cybersecurity situational awareness';
UPDATE `measures` SET `label1` = 'Sensibilização, educação e formação em segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security awareness, education and training';
UPDATE `measures` SET `label1` = 'A atividade de fornecedores de serviços externos é monitorizada para detetar potenciais eventos de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'External service provider activity is monitored to detect potential cybersecurity events';
UPDATE `measures` SET `label1` = 'Operações de Qualidade de Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data Quality Operations';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Proteção de Suportes de Armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Protection Policy and Procedures';
UPDATE `measures` SET `label1` = 'Resposta a Falhas no Processamento de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response to Audit Processing Failures';
UPDATE `measures` SET `label1` = 'Isolamento de Processos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Process Isolation';
UPDATE `measures` SET `label1` = 'Pessoal de Manutenção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Maintenance Personnel';
UPDATE `measures` SET `label1` = 'Eliminação de Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Disposal';
UPDATE `measures` SET `label1` = 'Autenticidade de Componentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Component Authenticity';
UPDATE `measures` SET `label1` = 'Informação em Recursos de Sistemas Partilhados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information in Shared Systems Resources';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Proteção Física e Ambiental', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical and Environmental Protection Policy and Procedures';
UPDATE `measures` SET `label1` = 'Verificação de Identidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identity Proofing';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Planeamento de Contingência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contingency Planning Policy and Procedures';
UPDATE `measures` SET `label1` = 'Plano de Resposta a Incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Response Plan';
UPDATE `measures` SET `label1` = 'Prevenção de fuga de dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data leakage prevention';
UPDATE `measures` SET `label1` = 'Direitos de acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access rights';
UPDATE `measures` SET `label1` = 'Certificados de Infraestrutura de Chave Pública', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Public Key Infrastructure Certificates';
UPDATE `measures` SET `label1` = 'As atividades de recuperação são comunicadas às partes interessadas internas e às equipas executivas e de gestão', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Recovery activities are communicated to internal stakeholders and executive and management teams';
UPDATE `measures` SET `label1` = 'Monitorização da Divulgação de Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Monitoring for Information Disclosure';
UPDATE `measures` SET `label1` = 'Trabalho em áreas seguras', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Working in secure areas';
UPDATE `measures` SET `label1` = 'Revisão, Análise e Reporte de Auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Review, Analysis, and Reporting';
UPDATE `measures` SET `label1` = 'Segurança Operacional', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Operations Security';
UPDATE `measures` SET `label1` = 'Utilização de Suportes de Armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Use';
UPDATE `measures` SET `label1` = 'As vulnerabilidades dos ativos são identificadas e documentadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Asset vulnerabilities are identified and documented';
UPDATE `measures` SET `label1` = 'Proteção contra Mineração de Dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data Mining Protection';
UPDATE `measures` SET `label1` = 'O pessoal conhece as suas funções e ordem de operações quando uma resposta é necessária', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel know their roles and order of operations when a response is needed';
UPDATE `measures` SET `label1` = 'Testes e Avaliação pelo Desenvolvedor', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Developer Testing and Evaluation';
UPDATE `measures` SET `label1` = 'Marcação de Componentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Component Marking';
UPDATE `measures` SET `label1` = 'Controlo de Acesso Individual', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Individual Access Control';
UPDATE `measures` SET `label1` = 'Mínimo Privilégio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Least Privilege';
UPDATE `measures` SET `label1` = 'São realizadas análises forenses', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Forensics are performed';
UPDATE `measures` SET `label1` = 'Segurança dos recursos humanos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Human resource security';
UPDATE `measures` SET `label1` = 'Funcionalidade Mínima', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Least Functionality';
UPDATE `measures` SET `label1` = 'Gestão de Autenticadores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authenticator Management';
UPDATE `measures` SET `label1` = 'Gestão de identidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identity management';
UPDATE `measures` SET `label1` = 'Os processos de governação e gestão de risco abordam os riscos de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Governance and risk management processes address cybersecurity risks';
UPDATE `measures` SET `label1` = 'Documentação do Sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Documentation';
UPDATE `measures` SET `label1` = 'Aviso de Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Notice';
UPDATE `measures` SET `label1` = 'Auditoria de Sessão', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Session Audit';
UPDATE `measures` SET `label1` = 'Dispositivos e Aplicações de Computação Colaborativa', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Collaborative Computing Devices and Applications';
UPDATE `measures` SET `label1` = 'As identidades são verificadas e associadas a credenciais e afirmadas nas interações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identities are proofed and bound to credentials and asserted in interactions';
UPDATE `measures` SET `label1` = 'Monitorização do Sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Monitoring';
UPDATE `measures` SET `label1` = 'Medidas de Desempenho', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Measures of Performance';
UPDATE `measures` SET `label1` = 'Desenvolvimento externalizado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Outsourced development';
UPDATE `measures` SET `label1` = 'Auditoria de segurança dos sistemas de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security audit';
UPDATE `measures` SET `label1` = 'Ciclo de Vida do Desenvolvimento de Sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Development Life Cycle';
UPDATE `measures` SET `label1` = 'Capacidade e Dados de Sensores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Sensor Capability and Data';
UPDATE `measures` SET `label1` = 'Os dados em repouso são protegidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data-at-rest is protected';
UPDATE `measures` SET `label1` = 'Honeyclients', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Honeyclients';
UPDATE `measures` SET `label1` = 'Registo de Divulgações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Accounting of Disclosures';
UPDATE `measures` SET `label1` = 'Autenticidade das Sessões', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Session Authenticity';
UPDATE `measures` SET `label1` = 'Câmaras de Detonação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detonation Chambers';
UPDATE `measures` SET `label1` = 'Heterogeneidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Heterogeneity';
UPDATE `measures` SET `label1` = 'Plano de Gestão de Risco da Cadeia de Fornecimento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Supply Chain Risk Management Plan';
UPDATE `measures` SET `label1` = 'Sincronização de relógios', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Clock synchronization';
UPDATE `measures` SET `label1` = 'Terminação de Sessão', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Session Termination';
UPDATE `measures` SET `label1` = 'Transferência de Pessoal', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel Transfer';
UPDATE `measures` SET `label1` = 'Especificação de Finalidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Purpose Specification';
UPDATE `measures` SET `label1` = 'Inteligência de ameaças', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Threat intelligence';
UPDATE `measures` SET `label1` = 'Funções e responsabilidades em segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security roles and responsibilities';
UPDATE `measures` SET `label1` = 'Restrições de Acesso para Alterações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Restrictions for Change';
UPDATE `measures` SET `label1` = 'Controlo de acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access control';
UPDATE `measures` SET `label1` = 'Autorização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authorization';
UPDATE `measures` SET `label1` = 'Entrega e Remoção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Delivery and Removal';
UPDATE `measures` SET `label1` = 'O ambiente físico é monitorizado para detetar potenciais eventos de cibersegurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The physical environment is monitored to detect potential cybersecurity events';
UPDATE `measures` SET `label1` = 'Identificação e Autenticação (Utilizadores Não Organizacionais)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identification and Authentication (Non-Organizational Users)';
UPDATE `measures` SET `label1` = 'Definições de Configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration Settings';
UPDATE `measures` SET `label1` = 'Resposta a Derramamento de Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Spillage Response';
UPDATE `measures` SET `label1` = 'Contactos com Grupos e Associações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contacts with Groups and Associations';
UPDATE `measures` SET `label1` = 'Processo de gestão de crises', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Crisis management process';
UPDATE `measures` SET `label1` = 'Aplicação do Fluxo de Informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Flow Enforcement';
UPDATE `measures` SET `label1` = 'Proteção de Informação Não Classificada Controlada em Sistemas Externos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protecting Controlled Unclassified Information on External Systems';
UPDATE `measures` SET `label1` = 'Acordos de confidencialidade ou não divulgação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Confidentiality or non-disclosure agreements';
UPDATE `measures` SET `label1` = 'Minimização de Informação Pessoalmente Identificável', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Minimization of Personally Identifiable Information';
UPDATE `measures` SET `label1` = 'Cópia de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information backup';
UPDATE `measures` SET `label1` = 'Categorização de Segurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security Categorization';
UPDATE `measures` SET `label1` = 'Identificação e Autenticação de Dispositivos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Device Identification and Authentication';
UPDATE `measures` SET `label1` = 'Os processos de gestão de risco são estabelecidos, geridos e acordados pelas partes interessadas da organização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk management processes are established, managed, and agreed to by organizational stakeholders';
UPDATE `measures` SET `label1` = 'Autorizações de Acesso Físico', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical Access Authorizations';
UPDATE `measures` SET `label1` = 'É mantida capacidade adequada para garantir a disponibilidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Adequate capacity to ensure availability is maintained';
UPDATE `measures` SET `label1` = 'Monitorização do Acesso Físico', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Monitoring Physical Access';
UPDATE `measures` SET `label1` = 'Auditoria entre Organizações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cross-Organizational Auditing';
UPDATE `measures` SET `label1` = 'Responsabilidades após cessação ou mudança de emprego', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Responsibilities after termination or change of employment';
UPDATE `measures` SET `label1` = 'É realizada monitorização de pessoal, ligações, dispositivos e software não autorizados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Monitoring for unauthorized personnel, connections, devices, and software is performed';
UPDATE `measures` SET `label1` = 'Os planos de resposta e recuperação são testados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response and recovery plans are tested';
UPDATE `measures` SET `label1` = 'Avaliação de Impacto sobre a Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Privacy Impact Assessment';
UPDATE `measures` SET `label1` = 'São utilizados mecanismos de verificação de integridade para verificar a integridade de software, firmware e informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Integrity checking mechanisms are used to verify software, firmware, and information integrity';
UPDATE `measures` SET `label1` = 'As notificações dos sistemas de deteção são investigadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Notifications from detection systems are investigated';
UPDATE `measures` SET `label1` = 'Segurança da informação na utilização de serviços de cloud', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security for use of cloud services';
UPDATE `measures` SET `label1` = 'São implementadas proteções contra fuga de dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protections against data leaks are implemented';
UPDATE `measures` SET `label1` = 'Testes de Resposta a Incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Response Testing';
UPDATE `measures` SET `label1` = 'Gestão de capacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Capacity management';
UPDATE `measures` SET `label1` = 'Controlo de Acesso para Dispositivos de Saída', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Control for Output Devices';
UPDATE `measures` SET `label1` = 'Os incidentes são mitigados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incidents are mitigated';
UPDATE `measures` SET `label1` = 'Relatório de Incidente', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Report';
UPDATE `measures` SET `label1` = 'As dependências e funções críticas para a prestação de serviços críticos são estabelecidas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Dependencies and critical functions for delivery of critical services are established';
UPDATE `measures` SET `label1` = 'São realizadas verificações de vulnerabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Vulnerability scans are performed';
UPDATE `measures` SET `label1` = 'Política e Procedimentos de Controlo de Acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Control Policy and Procedures';
UPDATE `measures` SET `label1` = 'Processo de Autorização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authorization Process';
UPDATE `measures` SET `label1` = 'A reputação após um evento é restaurada', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Reputation after an event is repaired';
UPDATE `measures` SET `label1` = 'Arquitetura Empresarial', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Enterprise Architecture';
UPDATE `measures` SET `label1` = 'Reporte de eventos de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security event reporting';
UPDATE `measures` SET `label1` = 'Proteção Criptográfica', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cryptographic Protection';
UPDATE `measures` SET `label1` = 'Autoridade para Recolha', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authority to Collect';
UPDATE `measures` SET `label1` = 'Acesso remoto', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Remote access';
UPDATE `measures` SET `label1` = 'As políticas e regulamentos relativos ao ambiente físico de operação dos ativos organizacionais são cumpridos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Policy and regulations regarding the physical operating environment for organizational assets are met';
UPDATE `measures` SET `label1` = 'As estratégias de resposta são atualizadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response strategies are updated';
UPDATE `measures` SET `label1` = 'Autenticação Adaptativa', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Adaptive Authentication';
UPDATE `measures` SET `label1` = 'Resposta ao Risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk Response';
UPDATE `measures` SET `label1` = 'Controlo de Acesso para Transmissões', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Control for Transmission';
UPDATE `measures` SET `label1` = 'Procedimentos de Falha Segura', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Fail-Safe Procedures';
UPDATE `measures` SET `label1` = 'Proteção contra software malicioso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protection against malware';
UPDATE `measures` SET `label1` = 'Processamento e Armazenamento Distribuídos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Distributed Processing and Storage';
UPDATE `measures` SET `label1` = 'Controlo de Acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Enforcement';
UPDATE `measures` SET `label1` = 'Monitorização de segurança física', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical security monitoring';
UPDATE `measures` SET `label1` = 'As plataformas de software e aplicações da organização estão inventariadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Software platforms and applications within the organization are inventoried';
UPDATE `measures` SET `label1` = 'Autenticação e identificação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authentication and identification';
UPDATE `measures` SET `label1` = 'Os fornecedores e parceiros terceiros são regularmente avaliados através de auditorias, resultados de testes ou outras formas de avaliação para confirmar que cumprem as suas obrigações contratuais', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Suppliers and third-party partners are routinely assessed using audits, test results, or other forms of evaluations to confirm they are meeting their contractual obligations.';
UPDATE `measures` SET `label1` = 'Resposta a incidentes de segurança de sistemas de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security incident response';
UPDATE `measures` SET `label1` = 'Partilha de Informação com Entidades Externas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Sharing With External Parties';
UPDATE `measures` SET `label1` = 'Gestão de recuperação de desastres', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Disaster recovery management';
UPDATE `measures` SET `label1` = 'Tentativas de Autenticação Sem Sucesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Unsuccessful Logon Attempts';
UPDATE `measures` SET `label1` = 'Proteção contra Negação de Serviço', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Denial of Service Protection';
UPDATE `measures` SET `label1` = 'Acesso a Portas e Dispositivos de E/S', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Port and I/O Device Access';
UPDATE `measures` SET `label1` = 'As atividades de deteção cumprem todos os requisitos aplicáveis', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detection activities comply with all applicable requirements';
UPDATE `measures` SET `label1` = 'Verificação das Funções de Segurança e Privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Function Verification';
UPDATE `measures` SET `label1` = 'Devolução de ativos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Return of assets';
UPDATE `measures` SET `label1` = 'Comunicação com autoridades competentes e CSIRTs', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Communication with competent authorities and CSIRTs';
UPDATE `measures` SET `label1` = 'Não-Persistência', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Non-Persistence';
UPDATE `measures` SET `label1` = 'Utilitários de apoio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Supporting utilities';
UPDATE `measures` SET `label1` = 'Utilização de Sistemas Externos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Use of External Systems';
UPDATE `measures` SET `label1` = 'Criptografia', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cryptography';
UPDATE `measures` SET `label1` = 'Designação de Risco do Cargo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Position Risk Designation';
