-- Portuguese label translations – measures (batch A, rows 1-170)
-- Source: label2 (English). label3/label4 cleared.
SET NAMES utf8mb4;

UPDATE `measures` SET `label1` = 'Separação dos ambientes de desenvolvimento, teste e produção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Separation of development, test and production environments';
UPDATE `measures` SET `label1` = 'Classificação da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Labelling of information';
UPDATE `measures` SET `label1` = 'Segurança do cabeamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cabling security';
UPDATE `measures` SET `label1` = 'Serviços de telecomunicações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Telecommunications Services';
UPDATE `measures` SET `label1` = 'Acordos de acesso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Agreements';
UPDATE `measures` SET `label1` = 'Os planos de resposta incorporam as lições aprendidas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response plans incorporate lessons learned';
UPDATE `measures` SET `label1` = 'Todos os utilizadores são informados e treinados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'All users are informed and trained';
UPDATE `measures` SET `label1` = 'Política de segurança do sistema de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security policy';
UPDATE `measures` SET `label1` = 'As informações sobre a deteção de eventos são comunicadas às partes adequadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Event detection information is communicated to appropriate parties';
UPDATE `measures` SET `label1` = 'Transporte de suportes de armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Transport';
UPDATE `measures` SET `label1` = 'O acesso a sistemas e ativos é controlado, incorporando o princípio da funcionalidade mínima', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access to systems and assets is controlled, incorporating the principle of least functionality';
UPDATE `measures` SET `label1` = 'Análise de risco de segurança do sistema de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information system security risk analysis';
UPDATE `measures` SET `label1` = 'Filtragem de saída de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Output Filtering';
UPDATE `measures` SET `label1` = 'Os processos de gestão de risco da cadeia de abastecimento cibernética são identificados, estabelecidos, avaliados, geridos e acordados pelas partes interessadas da organização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cyber supply chain risk management processes are identified, established, assessed, managed, and agreed to by organizational stakeholders';
UPDATE `measures` SET `label1` = 'As informações sobre ameaças e vulnerabilidades são recebidas de fóruns e fontes de partilha de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Threat and vulnerability information is received from information sharing forums and sources';
UPDATE `measures` SET `label1` = 'Ligações internas ao sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Internal System Connections';
UPDATE `measures` SET `label1` = 'Controlo de acesso físico', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical Access Control';
UPDATE `measures` SET `label1` = 'Política de secretária limpa e ecrã limpo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Clear desk and clear screen';
UPDATE `measures` SET `label1` = 'Proteção contra ameaças físicas e ambientais', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Protecting against physical and environmental threats';
UPDATE `measures` SET `label1` = 'Planeamento e preparação da gestão de incidentes de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security incident management planning and preparation';
UPDATE `measures` SET `label1` = 'Mascaramento de dados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data masking';
UPDATE `measures` SET `label1` = 'Processo de plano de ação e marcos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Plan of Action and Milestones Process';
UPDATE `measures` SET `label1` = 'Manutenção de equipamentos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Equipment maintenance';
UPDATE `measures` SET `label1` = 'Desconexão de rede', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Network Disconnect';
UPDATE `measures` SET `label1` = 'Tratamento da segurança da informação nos acordos com fornecedores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Addressing information security within supplier agreements';
UPDATE `measures` SET `label1` = 'Avaliação e decisão sobre eventos de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Assessment and decision on information security events';
UPDATE `measures` SET `label1` = 'Plano de ação e marcos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Plan of Action and Milestones';
UPDATE `measures` SET `label1` = 'O impacto do incidente é compreendido', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The impact of the incident is understood';
UPDATE `measures` SET `label1` = 'Organização de gestão de crises', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Crisis management organization';
UPDATE `measures` SET `label1` = 'O plano de recuperação é executado durante ou após um evento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Recovery plan is executed during or after an event';
UPDATE `measures` SET `label1` = 'Vulnerabilidades recentemente identificadas são mitigadas ou documentadas como riscos aceites', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Newly identified vulnerabilities are mitigated or documented as accepted risks';
UPDATE `measures` SET `label1` = 'Política e procedimentos de auditoria e responsabilização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit and Accountability Policy and Procedures';
UPDATE `measures` SET `label1` = 'Software instalado pelos utilizadores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'User-Installed Software';
UPDATE `measures` SET `label1` = 'Os suportes amovíveis são protegidos e a sua utilização restringida de acordo com a política', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Removable media is protected and its use restricted according to policy';
UPDATE `measures` SET `label1` = 'Os dados são destruídos de acordo com a política', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data is destroyed according to policy';
UPDATE `measures` SET `label1` = 'Monitorização de incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Monitoring';
UPDATE `measures` SET `label1` = 'Canais fora de banda', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Out-of-Band Channels';
UPDATE `measures` SET `label1` = 'Suportes de armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Storage media';
UPDATE `measures` SET `label1` = 'Gestão de ativos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Asset Management';
UPDATE `measures` SET `label1` = 'Política e procedimentos de proteção de sistemas e comunicações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System and Communications Protection Policy and Procedures';
UPDATE `measures` SET `label1` = 'Acesso a suportes de armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Access';
UPDATE `measures` SET `label1` = 'Entrada física', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical entry';
UPDATE `measures` SET `label1` = 'Formação em resposta a incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Response Training';
UPDATE `measures` SET `label1` = 'Utilizadores, dispositivos e outros ativos são autenticados (p. ex., fator único, multifator) de forma proporcional ao risco da transação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Users, devices, and other assets are authenticated (e.g., single-factor, multi-factor) commensurate with the risk of the transaction (e.g., individuals\' security and privacy risks and other organizational risks)';
UPDATE `measures` SET `label1` = 'Segurança física e ambiental', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical and environmental security';
UPDATE `measures` SET `label1` = 'Programas executáveis não modificáveis', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Non-Modifiable Executable Programs';
UPDATE `measures` SET `label1` = 'Proteção contra código malicioso', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Malicious Code Protection';
UPDATE `measures` SET `label1` = 'Gestão de reclamações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Complaint Management';
UPDATE `measures` SET `label1` = 'Tratamento de erros', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Error Handling';
UPDATE `measures` SET `label1` = 'Identificação e autenticação de serviços', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Service Identification and Authentication';
UPDATE `measures` SET `label1` = 'Utilização de criptografia', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Use of cryptography';
UPDATE `measures` SET `label1` = 'As prioridades para a missão, objetivos e atividades organizacionais são estabelecidas e comunicadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Priorities for organizational mission, objectives, and activities are established and communicated';
UPDATE `measures` SET `label1` = 'Acesso remoto', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Remote Access';
UPDATE `measures` SET `label1` = 'Registo de eventos (logging)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Logging';
UPDATE `measures` SET `label1` = 'As ameaças, tanto internas como externas, são identificadas e documentadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Threats, both internal and external, are identified and documented';
UPDATE `measures` SET `label1` = 'Retroinformação do autenticador', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Authenticator Feedback';
UPDATE `measures` SET `label1` = 'Aprendizagem com incidentes de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Learning from information security incidents';
UPDATE `measures` SET `label1` = 'Autenticação segura', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure authentication';
UPDATE `measures` SET `label1` = 'Local de processamento alternativo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternate Processing Site';
UPDATE `measures` SET `label1` = 'Os contratos com fornecedores e parceiros terceiros são utilizados para implementar medidas adequadas ao programa de cibersegurança da organização e ao Plano de Gestão de Risco da Cadeia de Abastecimento Cibernética', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contracts with suppliers and third-party partners are used to implement appropriate measures designed to meet the objectives of an organizationâs cybersecurity program and Cyber Supply Chain Risk Management Plan.';
UPDATE `measures` SET `label1` = 'Os incidentes são categorizados de forma consistente com os planos de resposta', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incidents are categorized consistent with response plans';
UPDATE `measures` SET `label1` = 'Avaliações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Assessments';
UPDATE `measures` SET `label1` = 'Prevenção de falhas previsíveis', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Predictable Failure Prevention';
UPDATE `measures` SET `label1` = 'Transferência de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information transfer';
UPDATE `measures` SET `label1` = 'Aviso de utilização do sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Use Notification';
UPDATE `measures` SET `label1` = 'Testes de penetração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Penetration Testing';
UPDATE `measures` SET `label1` = 'Triagem de pessoal', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel Screening';
UPDATE `measures` SET `label1` = 'Os dispositivos físicos e sistemas dentro da organização estão inventariados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical devices and systems within the organization are inventoried';
UPDATE `measures` SET `label1` = 'Segurança da informação nas relações com fornecedores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security in supplier relationships';
UPDATE `measures` SET `label1` = 'Gestão de identificadores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Identifier Management';
UPDATE `measures` SET `label1` = 'Os processos de deteção são testados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Detection processes are tested';
UPDATE `measures` SET `label1` = 'Fuga de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Leakage';
UPDATE `measures` SET `label1` = 'Codificação segura', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure coding';
UPDATE `measures` SET `label1` = 'É estabelecida e gerida uma linha de base das operações de rede e dos fluxos de dados esperados para utilizadores e sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'A baseline of network operations and expected data flows for users and systems is established and managed';
UPDATE `measures` SET `label1` = 'Controlo de acesso para dispositivos móveis', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Access Control for Mobile Devices';
UPDATE `measures` SET `label1` = 'Relações com o ecossistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Ecosystem relations';
UPDATE `measures` SET `label1` = 'Dispositivos endpoint de utilizadores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'User endpoint devices';
UPDATE `measures` SET `label1` = 'Perímetros de segurança física', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical security perimeters';
UPDATE `measures` SET `label1` = 'Controlo de alterações à configuração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Configuration Change Control';
UPDATE `measures` SET `label1` = 'Os incidentes são contidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incidents are contained';
UPDATE `measures` SET `label1` = 'Trabalho remoto', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Remote working';
UPDATE `measures` SET `label1` = 'Resistência e deteção de adulteração', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Tamper Resistance and Detection';
UPDATE `measures` SET `label1` = 'Caminho de confiança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Trusted Path';
UPDATE `measures` SET `label1` = 'Funções do programa de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Security Program Roles';
UPDATE `measures` SET `label1` = 'As funções e responsabilidades de segurança da informação são coordenadas e alinhadas com as funções internas e os parceiros externos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security roles & responsibilities are coordinated and aligned with internal roles and external partners';
UPDATE `measures` SET `label1` = 'Enquadramento do risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk Framing';
UPDATE `measures` SET `label1` = 'Plano de infraestruturas críticas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Critical Infrastructure Plan';
UPDATE `measures` SET `label1` = 'A informação é partilhada de forma consistente com os planos de resposta', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information is shared consistent with response plans';
UPDATE `measures` SET `label1` = 'As cópias de segurança da informação são realizadas, mantidas e testadas periodicamente', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Backups of information are conducted, maintained, and tested periodically';
UPDATE `measures` SET `label1` = 'Monitorização e rastreamento de ativos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Asset Monitoring and Tracking';
UPDATE `measures` SET `label1` = 'Tratamento e retenção de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Handling and Retention';
UPDATE `measures` SET `label1` = 'Controlo de sessões simultâneas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Concurrent Session Control';
UPDATE `measures` SET `label1` = 'Monitorização, revisão e gestão de alterações dos serviços de fornecedores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Monitoring, review and change management of supplier services';
UPDATE `measures` SET `label1` = 'É criada e mantida uma configuração de base dos sistemas de tecnologia de informação/sistemas de controlo industrial', `label3` = NULL, `label4` = NULL WHERE `label2` = 'A baseline configuration of information technology/industrial control systems is created and maintained';
UPDATE `measures` SET `label1` = 'Retenção de registos de auditoria', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit Record Retention';
UPDATE `measures` SET `label1` = 'Os eventos são reportados de forma consistente com os critérios estabelecidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Events are reported consistent with established criteria';
UPDATE `measures` SET `label1` = 'Os dados de eventos são agregados e correlacionados a partir de múltiplas fontes e sensores', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Event data are aggregated and correlated from multiple sources and sensors';
UPDATE `measures` SET `label1` = 'Contacto com grupos de interesse especial', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contact with special interest groups';
UPDATE `measures` SET `label1` = 'Atributos de segurança e privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Attributes';
UPDATE `measures` SET `label1` = 'A coordenação com as partes interessadas ocorre de forma consistente com os planos de resposta', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Coordination with stakeholders occurs consistent with response plans';
UPDATE `measures` SET `label1` = 'Aviso de registo de sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System of Records Notice';
UPDATE `measures` SET `label1` = 'Transmissão de atributos de segurança e privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Transmission of Security and Privacy Attributes';
UPDATE `measures` SET `label1` = 'Separação de funções', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Separation of Duties';
UPDATE `measures` SET `label1` = 'Inventário de componentes do sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Component Inventory';
UPDATE `measures` SET `label1` = 'Os dados em trânsito são protegidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Data-in-transit is protected';
UPDATE `measures` SET `label1` = 'O acesso físico aos ativos é gerido e protegido', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Physical access to assets is managed and protected';
UPDATE `measures` SET `label1` = 'Configuração de base', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Baseline Configuration';
UPDATE `measures` SET `label1` = 'Arquiteturas de segurança e privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Architectures';
UPDATE `measures` SET `label1` = 'Política e procedimentos de planeamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Planning Policy and Procedures';
UPDATE `measures` SET `label1` = 'Plano do programa de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Security Program Plan';
UPDATE `measures` SET `label1` = 'Segurança das redes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Networks security';
UPDATE `measures` SET `label1` = 'Direitos de propriedade intelectual', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Intellectual property rights';
UPDATE `measures` SET `label1` = 'Alertas, avisos e diretivas de segurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security Alerts, Advisories, and Directives';
UPDATE `measures` SET `label1` = 'Os registos de auditoria/log são determinados, documentados, implementados e revistos de acordo com a política', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Audit/log records are determined, documented, implemented, and reviewed in accordance with policy';
UPDATE `measures` SET `label1` = 'Ciclo de vida de desenvolvimento seguro', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure development life cycle';
UPDATE `measures` SET `label1` = 'Tratamento de incidentes', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident Handling';
UPDATE `measures` SET `label1` = 'São implementados mecanismos (p. ex., à prova de falha, balanceamento de carga, substituição a quente) para alcançar os requisitos de resiliência em situações normais e adversas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Mechanisms (e.g., failsafe, load balancing, hot swap) are implemented to achieve resilience requirements in normal and adverse situations';
UPDATE `measures` SET `label1` = 'Política e procedimentos de segurança de pessoal', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel Security Policy and Procedures';
UPDATE `measures` SET `label1` = 'O impacto dos eventos é determinado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Impact of events is determined';
UPDATE `measures` SET `label1` = 'Formação de sensibilização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Awareness Training';
UPDATE `measures` SET `label1` = 'Conformidade com políticas, regras e normas de segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Compliance with policies, rules and standards for information security';
UPDATE `measures` SET `label1` = 'Consentimento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Consent';
UPDATE `measures` SET `label1` = 'Divulgação de informação sobre o programa de privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Dissemination of Privacy Program Information';
UPDATE `measures` SET `label1` = 'Particionamento do sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Partitioning';
UPDATE `measures` SET `label1` = 'Revisão independente da segurança da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Independent review of information security';
UPDATE `measures` SET `label1` = 'As estratégias de recuperação são atualizadas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Recovery strategies are updated';
UPDATE `measures` SET `label1` = 'A cibersegurança está incluída nas práticas de recursos humanos (p. ex., desprovisionamento, triagem de pessoal)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Cybersecurity is included in human resources practices (e.g., deprovisioning, personnel screening)';
UPDATE `measures` SET `label1` = 'Recolha de evidências', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Collection of evidence';
UPDATE `measures` SET `label1` = 'Capacidade de auditoria alternativa', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternate Audit Capability';
UPDATE `measures` SET `label1` = 'Eliminação segura ou reutilização de equipamentos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure disposal or re-use of equipment';
UPDATE `measures` SET `label1` = 'Estratégia de gestão de risco', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Risk Management Strategy';
UPDATE `measures` SET `label1` = 'Isolamento de funções de segurança', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security Function Isolation';
UPDATE `measures` SET `label1` = 'Segurança da informação na gestão de projetos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information security in project management';
UPDATE `measures` SET `label1` = 'O papel da organização na cadeia de abastecimento é identificado e comunicado', `label3` = NULL, `label4` = NULL WHERE `label2` = 'The organization\'s role in the supply chain is identified and communicated';
UPDATE `measures` SET `label1` = 'Política e procedimentos de sensibilização e formação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Awareness and Training Policy and Procedures';
UPDATE `measures` SET `label1` = 'Segurança de escritórios, salas e instalações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Securing offices, rooms and facilities';
UPDATE `measures` SET `label1` = 'Serviço seguro de resolução de nomes/endereços (fonte autoritativa)', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure Name / Address Resolution Service (Authoritative Source)';
UPDATE `measures` SET `label1` = 'Segurança dos serviços de rede', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security of network services';
UPDATE `measures` SET `label1` = 'As partes interessadas terceiras (p. ex., fornecedores, clientes, parceiros) compreendem as suas funções e responsabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Third-party stakeholders (e.g., suppliers, customers, partners) understand roles & responsibilities';
UPDATE `measures` SET `label1` = 'As funções e responsabilidades de deteção são bem definidas para garantir a responsabilização', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Roles and responsibilities for detection are well defined to ensure accountability';
UPDATE `measures` SET `label1` = 'Particionamento de aplicações', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Application Partitioning';
UPDATE `measures` SET `label1` = 'É desenvolvido e implementado um plano de gestão de vulnerabilidades', `label3` = NULL, `label4` = NULL WHERE `label2` = 'A vulnerability management plan is developed and implemented';
UPDATE `measures` SET `label1` = 'Bloqueio de dispositivo', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Device Lock';
UPDATE `measures` SET `label1` = 'Inventário de informação e outros ativos associados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Inventory of information and other associated assets';
UPDATE `measures` SET `label1` = 'Princípios de arquitetura e engenharia de sistemas seguros', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Secure system architecture and engineering principles';
UPDATE `measures` SET `label1` = 'Sanções ao pessoal', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel Sanctions';
UPDATE `measures` SET `label1` = 'Administração de sistemas de informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Administration information systems';
UPDATE `measures` SET `label1` = 'Procedimentos operacionais documentados', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Documented operating procedures';
UPDATE `measures` SET `label1` = 'Testes ao plano de continuidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contingency Plan Testing';
UPDATE `measures` SET `label1` = 'Prontidão das TIC para a continuidade do negócio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'ICT readiness for business continuity';
UPDATE `measures` SET `label1` = 'Classificação da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Classification of information';
UPDATE `measures` SET `label1` = 'Cessação de funções do pessoal', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Personnel Termination';
UPDATE `measures` SET `label1` = 'Análises de impacto de segurança e privacidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Security and Privacy Impact Analyses';
UPDATE `measures` SET `label1` = 'Os requisitos legais e regulamentares em matéria de cibersegurança, incluindo as obrigações de privacidade e liberdades civis, são compreendidos e geridos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Legal and regulatory requirements regarding cybersecurity, including privacy and civil liberties obligations, are understood and managed';
UPDATE `measures` SET `label1` = 'Plano de continuidade', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Contingency Plan';
UPDATE `measures` SET `label1` = 'Os planos de resposta (Resposta a Incidentes e Continuidade do Negócio) e os planos de recuperação (Recuperação de Incidentes e Recuperação de Desastres) estão em vigor e são geridos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Response plans (Incident Response and Business Continuity) and recovery plans (Incident Recovery and Disaster Recovery) are in place and managed';
UPDATE `measures` SET `label1` = 'Armazenamento de suportes de armazenamento', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Media Storage';
UPDATE `measures` SET `label1` = 'Localização da informação', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Information Location';
UPDATE `measures` SET `label1` = 'Ferramentas de manutenção', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Maintenance Tools';
UPDATE `measures` SET `label1` = 'Os recursos (p. ex., hardware, dispositivos, dados e software) são priorizados com base na sua classificação, criticidade e valor para o negócio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Resources (e.g., hardware, devices, data, and software) are prioritized based on their classification, criticality, and business value';
UPDATE `measures` SET `label1` = 'Inventário de sistemas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System Inventory';
UPDATE `measures` SET `label1` = 'Proteção contra incêndio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Fire Protection';
UPDATE `measures` SET `label1` = 'Monitorização contínua', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Continuous Monitoring';
UPDATE `measures` SET `label1` = 'Mecanismos de segurança alternativos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Alternative Security Mechanisms';
UPDATE `measures` SET `label1` = 'Os planos de recuperação incorporam as lições aprendidas', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Recovery plans incorporate lessons learned';
UPDATE `measures` SET `label1` = 'Os limiares de alerta para incidentes são estabelecidos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Incident alert thresholds are established';
UPDATE `measures` SET `label1` = 'Não-repúdio', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Non-repudiation';
UPDATE `measures` SET `label1` = 'Localização dos componentes do sistema', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Location of System Components';
UPDATE `measures` SET `label1` = 'Política e procedimentos de aquisição de sistemas e serviços', `label3` = NULL, `label4` = NULL WHERE `label2` = 'System and Services Acquisition Policy and Procedures';
UPDATE `measures` SET `label1` = 'Alocação de recursos', `label3` = NULL, `label4` = NULL WHERE `label2` = 'Allocation of Resources';
