-- Portuguese label translations – rolf_risks.description
-- Sets description1=PT, description3=NULL, description4=NULL; description2 (EN) unchanged.
SET NAMES utf8mb4;

UPDATE `rolf_risks` SET `description1` = 'Para detalhes completos sobre as "regras vinculativas da empresa" consulte o artigo 47.\nSe as secções 46 e 47 não puderem ser cumpridas e a transferência tiver ainda de ser realizada, consulte:\n   - 48: Transferências ou divulgações não autorizadas pelo direito da União\n   - 49: Derrogações para situações específicas\nNota: Neste ponto, deve ser realizado um estudo aprofundado de forma a garantir o cumprimento do RGPD no que respeita às "Transferências"\n(Art. 47, 48, 49)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Absence of binding corporate rules';

UPDATE `rolf_risks` SET `description1` = 'Obrigações relativas à proteção de dados pessoais\nOs limites do tratamento sob instrução do responsável pelo tratamento\n(múltiplos artigos)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Absence of contractual clauses between the controller and the processor';

UPDATE `rolf_risks` SET `description1` = 'O responsável pelo tratamento e o subcontratante devem em qualquer caso designar um encarregado da proteção de dados quando:\na) o tratamento seja efetuado por uma autoridade ou organismo público, à exceção dos tribunais no exercício da sua função jurisdicional\nb) as atividades principais do responsável pelo tratamento ou do subcontratante consistam em operações de tratamento que, pela sua natureza, âmbito e/ou finalidades, exijam um controlo regular e sistemático dos titulares dos dados em grande escala\nc) as atividades principais do responsável pelo tratamento ou do subcontratante consistam no tratamento em grande escala de categorias especiais de dados nos termos do artigo 9 e de dados pessoais relativos a condenações penais e infrações referidas no artigo 10\n(Art. 37.1)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Absence of DPO, when required by law';

UPDATE `rolf_risks` SET `description1` = 'Que tipo de alteração?\n  - Alteração ou outra finalidade?\n  - Novos destinatários?\n  - A duração do tratamento?\n  - ...?\n(Art. 13.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Changes in treatment or further treatment, without prior notification to the data subject';

UPDATE `rolf_risks` SET `description1` = 'Nas fases iniciais de conceção de um novo tratamento, a segurança dos dados é tida em consideração?\nO cumprimento do RGPD é tido em consideração?\n(Art. 25)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'During the design phase of new projects, data protection by design and by default are not taken into account';

UPDATE `rolf_risks` SET `description1` = 'Adequados, pertinentes e limitados ao que é necessário face às finalidades?\nO princípio da minimização dos dados é respeitado?\nOs dados recolhidos contribuem para alcançar a finalidade do tratamento?\nSão compatíveis com a mesma?\nEstão atualizados?\n(Art 5.1c, 5.1d)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Excessive collect of personal data according to the purpose of the processing';

UPDATE `rolf_risks` SET `description1` = 'Com que frequência são recebidos pedidos?\n(Capítulo III)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Excessive response time for answering requests';

UPDATE `rolf_risks` SET `description1` = 'Requisitos legais e regulamentares\nComunicação com fornecedores externos\nMonitorização do desempenho dos fornecedores', `description3` = NULL, `description4` = NULL WHERE `label2` = 'External providers jeopardize the quality of the process';

UPDATE `rolf_risks` SET `description1` = 'Existe um procedimento de controlo?\nQuem é o responsável?\nQual é o período de lançamento?\n(Art. 17)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Failure to control the deletion of data reaching the end of the shelf life';

UPDATE `rolf_risks` SET `description1` = 'As obrigações respetivas estão claramente definidas? De forma formal?\nO titular dos dados é informado dos acordos entre co-responsáveis (pelo menos nas suas linhas gerais)?\nSabe de forma inequívoca como e a quem se deve dirigir para exercer todos os seus direitos?\n(Art. 26)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'In the case of joint responsibility for processing, responsibilities are not clearly defined';

UPDATE `rolf_risks` SET `description1` = 'A retificação é possível?\nEm todo o lado (Duplicações, diferentes suportes, ...)?\n(Art. 16)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Inability to correct inaccurate personal data';

UPDATE `rolf_risks` SET `description1` = 'Que formato de dados é esperado?\nEstruturado? De uso corrente e de leitura automática?\nSe transferido diretamente para outro responsável pelo tratamento, a transferência é aceite pelo responsável?\nNo caso de tratamento automatizado, se o titular dos dados exercer o seu direito à portabilidade dos dados, existe alguma disposição para que os dados passem diretamente para o novo responsável pelo tratamento?\n(Art. 20)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Inability to exercise the right to data portability';

UPDATE `rolf_risks` SET `description1` = 'Existe um ponto de contacto (correio, telefone, endereço)?\nExiste um procedimento em vigor?\nQual é o prazo para cessar o tratamento, após o pedido do titular dos dados?\nSe existirem vários tratamentos, é possível cessar apenas um?\nNota: Ver exceção\n(Art. 21)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Inability to object to the processing of personal data';

UPDATE `rolf_risks` SET `description1` = 'Aspetos sociais (ambiente calmo, não discriminatório);\nAspetos psicológicos (redução do stresse, prevenção do esgotamento, proteção emocional);\nAspetos físicos (temperatura, calor, humidade, luz, circulação de ar, higiene, ruído).', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Inadequate environment for the implementation of the process';

UPDATE `rolf_risks` SET `description1` = 'Existem transferências sucessivas?\nQual é o país terceiro? Como é avaliado o seu nível de proteção?\nExistem compromissos internacionais?\nQual é a posição da Comissão relativamente a esse país terceiro?\nNota: Consulte o Jornal Oficial da União Europeia para a categorização dos países no domínio da proteção de dados.\n(Art. 44, 45)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Inadequate level of protection of the third country';

UPDATE `rolf_risks` SET `description1` = 'Tem acesso às informações relevantes para as suas funções, a partir da direção da organização?\nEsta diretamente relacionado com a direção da organização?\nConflito de interesses com outras missões do EPD? CISO?\nFaz parte da direção da organização?\n(Art. 38)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Incompatibility between DPO functions and missions';

UPDATE `rolf_risks` SET `description1` = 'Como é prestada a informação?\nInformação a fornecer no mínimo:\n  - Finalidades do tratamento\n  - Categorias de DCP e respetivas fontes\n  - Destinatários ou categorias de destinatários\n  - O período de conservação dos dados ou os critérios utilizados para determinar essa duração\n  - A existência dos seus vários direitos\n  - A existência de decisão automatizada, incluindo a definição de perfis\n  - Em caso de transferência de DCP para um país terceiro ou organização internacional, informação sobre as garantias adequadas\n  - ...\n(Art. 15.1, 15.2)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Information on the access rights to be provided to the person is insufficient';

UPDATE `rolf_risks` SET `description1` = 'As instruções do responsável pelo tratamento são genéricas? Precisas? Interpretáveis?\nDireito de transferir DCP?\nEstado da arte em segurança da informação? (Art. 32)\n(Art 28.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Instructions from the controller are not documented';

UPDATE `rolf_risks` SET `description1` = 'É disponibilizado um formulário de pedido ao titular dos dados?\nOs pedidos são feitos por escrito, datados e assinados?\n(Capítulo III)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Insufficient evidence concerning applications for the exercise of rights';

UPDATE `rolf_risks` SET `description1` = 'O consentimento pode ser demonstrado?\nProva física? Eletrónica?\n(Art. 7.1)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Insufficient evidence of the consent collection';

UPDATE `rolf_risks` SET `description1` = 'Como são tratados os pedidos?\n(Capítulo III)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Insufficient resources to ensure the exercise of the data subject''s rights';

UPDATE `rolf_risks` SET `description1` = 'Quando proporcionado às atividades de tratamento:\n   - Existe um referencial de privacidade? Políticas? Cartas?\n   - Os colaboradores estão informados das medidas adotadas?\n(Art. 24)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of appropriate data protection policies';

UPDATE `rolf_risks` SET `description1` = 'Presença de regras vinculativas da empresa?\nPresença de instrumentos juridicamente vinculativos e executórios\nPresença de um código de conduta aprovado nos termos do artigo 40\nPresença de mecanismos de certificação aprovados nos termos do artigo 42\n(Art. 46)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of clauses for transfers to third countries not providing the appropriate level of protection';

UPDATE `rolf_risks` SET `description1` = 'Existe um procedimento de tratamento de reclamações?\nExiste acompanhamento?\nExiste um prazo para o tratamento da reclamação?\n(Art. 24)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of complaint management procedure';

UPDATE `rolf_risks` SET `description1` = 'As obrigações a definir: a finalidade e duração do tratamento, a natureza e objeto do tratamento, o tipo de DCP e as categorias de titulares dos dados, e as obrigações e direitos do responsável pelo tratamento.\nOs documentos são formais?\n(Art 28: 3, 28: 9)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of contractual clauses between the controller and the processor';

UPDATE `rolf_risks` SET `description1` = 'Questionário de satisfação', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of feedback from customers regarding products and services, including their claims';

UPDATE `rolf_risks` SET `description1` = 'Existe um procedimento de controlo de identidade? É formal?\nQue tipo de documento é solicitado?\nO documento é fotocopiado? Armazenado?\n(Capítulo III)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of identity check of the applicant';

UPDATE `rolf_risks` SET `description1` = 'Como fazer o pedido? Por correio eletrónico? Correio postal? Pessoalmente?\nO pedido é gratuito?\n(Capítulo III)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of information to the data subject on how to exercise its rights';

UPDATE `rolf_risks` SET `description1` = 'Existe um procedimento de notificação? Formal?\nContemplate toda a informação mínima a fornecer?\n  - À comissão (72h)?\n  - Ao titular dos dados?\n(Art. 33 e 34)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of procedure for notifying the commission of a breach of personal data';

UPDATE `rolf_risks` SET `description1` = 'Existe algum registo das atividades de tratamento?\nFormal? Está atualizado?\nExiste um inventário de todos os tratamentos do organismo? Estão incluídos no registo?\nExistem recolhas de DCP sem conhecimento claro das finalidades?\nCaso 1: Responsável pelo tratamento\n    - Consulte o Art. 30.1 para a informação mínima a registar\nCaso 2: Subcontratante\n    - Consulte o Art. 30.2 para a informação mínima a registar\nNota: Ver exceções com base no número de trabalhadores (250) ou categorias de DCP\n(Art. 30)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of records of processing activities';

UPDATE `rolf_risks` SET `description1` = 'Recursos humanos\nInfraestrutura\n Instalações e serviços associados\n Equipamentos, incluindo hardware e software\nMeios de transporte\nTecnologias de informação e comunicação.', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of resource planning required to implement and control the process.';

UPDATE `rolf_risks` SET `description1` = 'Tem formação académica em direito? Economia? Gestão? Informática? ...?\nÉ membro de uma das profissões regulamentadas? Advogados? Revisores de empresas? Contabilistas? Médicos?\nConhece bem o seu papel e funções?\n(Art. 37.5, 39.2)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of skills of the DPO';

UPDATE `rolf_risks` SET `description1` = 'Quem presta o consentimento?\nExiste verificação da responsabilidade parental sobre a criança?\n(Art. 8)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lack of the consent given or authorized by the holder of parental responsibility over the child (< 16 years old)';

UPDATE `rolf_risks` SET `description1` = 'Qual é a condição de licitude?\n  a) Recolha direta do consentimento da pessoa\n  b) O tratamento é necessário para a execução de um contrato\n  c) Necessário para o cumprimento de uma obrigação jurídica\n  d) Necessário para proteger os interesses vitais do titular dos dados\n  e) Necessário para o exercício de funções de interesse público\n  f) Necessário para efeitos dos interesses legítimos\n(Art. 6.1)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Lawfulness of the personal data processing';

UPDATE `rolf_risks` SET `description1` = 'Acompanhamento jurídico?\nPonto de contacto para consultas e reclamações?\n(Art 39.1d)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Low communication between DPO and the commission';

UPDATE `rolf_risks` SET `description1` = 'A retirada do consentimento é possível:\n  - A qualquer momento?\n  - Sem justificação?\n  - De forma facilmente acessível?\n  - A pessoa sabe que pode retirar o consentimento?\n(Art. 7.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'No means to allow the exercise of the right of withdrawal of consent';

UPDATE `rolf_risks` SET `description1` = 'Como é prestada a informação?\nOs dados fornecidos são exaustivos?\nExistem taxas administrativas? Proporcionalidade?\n(Art. 15.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'No means to provide a copy of the personal data to the data subject';

UPDATE `rolf_risks` SET `description1` = 'Válido para retificação, apagamento de dados e limitação do tratamento\n(Art. 19)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Notification to each recipient to whom personal data has been communicated is not provided';

UPDATE `rolf_risks` SET `description1` = 'Formação inicial ou profissional\nConhecimentos adquiridos através da experiência\nInformação documentada', `description3` = NULL, `description4` = NULL WHERE `label2` = 'People''s skill level is not appropriate';

UPDATE `rolf_risks` SET `description1` = 'Os dados transmitidos permitem alcançar a finalidade do tratamento e são compatíveis com a mesma?\nO princípio da minimização dos dados é respeitado?\n(Múltiplos artigos)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Personal data are excessive in relation to the purpose of the processing';

UPDATE `rolf_risks` SET `description1` = 'O EPD está ativo em temas como:\n  - Sensibilização?\n  - Aconselhamento aos colaboradores?\n  - Códigos de conduta?\n  - Políticas relativas à proteção de DCP\n(Artigo 39 (1) (b)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Poor communication between the DPO and employees';

UPDATE `rolf_risks` SET `description1` = 'Ajuda o responsável pelo tratamento a garantir o nível de proteção de dados?\nResponde aos pedidos dos titulares dos dados que o abordam para o exercício dos direitos previstos?\nResponde aos pedidos do responsável pelo tratamento (a pedido do exercício dos direitos do titular dos dados)?\nFornece ao responsável pelo tratamento todas as informações necessárias para demonstrar o cumprimento das suas obrigações?\n(Art 28.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Poor cooperation with the controller';

UPDATE `rolf_risks` SET `description1` = 'Quando um subcontratante recruta outro subcontratante para realizar atividades de tratamento específicas por conta do responsável pelo tratamento, devem aplicar-se as mesmas obrigações de proteção de dados estabelecidas no contrato ou outro ato jurídico entre o responsável pelo tratamento e o subcontratante.\n(Art 28, 29)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Poor subcontracting conditions in cascade';

UPDATE `rolf_risks` SET `description1` = 'Note-se que a informação depende da forma como é recolhida (diretamente da pessoa no artigo 13, caso contrário artigo 14)\nInformação a fornecer no mínimo:\n - A identidade e os contactos do responsável pelo tratamento ou do Encarregado da Proteção de Dados\n - Finalidades do tratamento\n - O fundamento jurídico do tratamento\n - Se o tratamento se basear em interesses legítimos, indicá-los\n - Destinatários ou categorias de destinatários\n - A intenção de transferir DCP para um país terceiro ou organização internacional\n - O período de conservação dos dados ou os critérios utilizados para determinar essa duração\n - A existência dos seus vários direitos\n - A existência de decisão automatizada, incluindo a definição de perfis, a lógica subjacente e a importância e consequências previstas desse tratamento para o titular dos dados\n - ...\n(Art. 13.1, 13.2, 14)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Prior information to be provided to the person is insufficient';

UPDATE `rolf_risks` SET `description1` = 'Distribuição, Acesso, Recuperação e Utilização;\nArmazenamento e proteção, incluindo preservação da legibilidade;\nControlo de alterações (ex. controlo de versões);\nArmazenamento e eliminação.', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Processes are not documented or updated';

UPDATE `rolf_risks` SET `description1` = 'O responsável pelo tratamento ou o subcontratante nomeou um representante de forma formal?\nVer o RGPD para as exceções.\n(Art. 27)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Representatives of the controllers or processors are not established in the Union';

UPDATE `rolf_risks` SET `description1` = 'Conformidade do produto\nAcordo com o cliente', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The applicable legal and regulatory requirements are not determined, understood and consistently met';

UPDATE `rolf_risks` SET `description1` = 'Se o tratamento for restringido, que medidas são tomadas pelo responsável pelo tratamento para garantir a limitação?\nSe a limitação for levantada, como será notificado o titular dos dados?\nNota: Ver exceções\n(Art. 18.2, 18.3)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The controller does not implement the means to limit the processing';

UPDATE `rolf_risks` SET `description1` = 'Utilização excessiva de agrupamento?\nOs locais de trabalho estão demasiado distantes?\nOs organismos são demasiado grandes?\nO EPD está sobrecarregado?\n(Art. 37.2, 37.3, 37.4)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The DPO is not reachable';

UPDATE `rolf_risks` SET `description1` = 'O período durante o qual os DCP serão conservados é determinado em função da finalidade do tratamento?\nQue critérios são utilizados para determinar o período de conservação dos DCP?\nÉ necessário conservar todos os DCP (minimização dos dados)?\n(Art 5.1e)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The period for which the personal data will be stored is inadequate';

UPDATE `rolf_risks` SET `description1` = 'Existem verificações periódicas? Auditorias? Certificados?\nAplicação de um código de conduta aprovado nos termos do artigo 40 ou de um mecanismo de certificação aprovado?\n(Art 28.1, 28.2, 28.5)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The processor does not have sufficient guarantees to ensure data protection';

UPDATE `rolf_risks` SET `description1` = 'Quais são as áreas de atividade da organização?\nQual é a finalidade do tratamento? Qual é a relação entre a organização e o titular dos dados?\nOs DCP são reutilizados para outras finalidades? Transferência? Estatísticas? Outro tratamento?\n(Art 5.1a, 5.1b)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The purposes of processing and the missions of the organization are not in adequacy';

UPDATE `rolf_risks` SET `description1` = 'Que tipo de legitimidade?\n  - Consentimento da pessoa\n  - Cumprimento de uma obrigação jurídica\n  - Execução de uma missão de serviço público\n  - Execução de um contrato\n  - Realização de um interesse legítimo\n  - Salvaguarda do interesse vital\n(múltiplos artigos)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'The recipient does not know the purpose of the processing';

UPDATE `rolf_risks` SET `description1` = 'Se a condição de licitude for cumprida pelas alíneas (b), (d) e (f) do artigo 6.1. A finalidade inclui, nomeadamente:\na) a existência de ligação entre as finalidades para as quais os DCP foram recolhidos e as finalidades do tratamento posterior previsto\nb) o contexto em que os DCP foram recolhidos\nc) a natureza dos DCP\nd) as possíveis consequências do tratamento posterior previsto para os titulares dos dados\ne) a existência de garantias adequadas, que podem incluir cifragem ou pseudonimização\n(Art. 6.4)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Treatment is unlawful for another purpose';

UPDATE `rolf_risks` SET `description1` = 'A obrigação de apagar os DCP aplica-se com base em determinados fundamentos: dados que já não são necessários, retirada do consentimento, oposição ao tratamento, tratamento ilícito, obrigação jurídica, oferta de serviços...)\nPossibilidade de apagamento do tratamento através de outros subcontratantes\nNota: Existem exceções à aplicação do direito ao apagamento (artigos 17-3)\n(Art. 17.1, 17.2)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Unable to delete personal data';

UPDATE `rolf_risks` SET `description1` = 'O titular dos dados tem o direito de obter do responsável pelo tratamento a limitação do tratamento quando se verificar uma das seguintes situações:\na) A exatidão dos DCP é contestada\nb) O tratamento é ilícito e o titular dos dados se opõe ao apagamento e requer em contrapartida a limitação da sua utilização\nc) o responsável pelo tratamento já não necessita dos DCP para fins de tratamento, mas o responsável ainda os necessita para efeitos de declaração, exercício ou defesa de direitos jurídicos\nd) o titular dos dados se opôs ao tratamento nos termos do artigo 21, n.º 1, durante a verificação de se os motivos legítimos prosseguidos pelo responsável pelo tratamento prevalecem sobre os do titular dos dados.\n(Art. 18.1)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Unable to exercise the right to limit the processing';

UPDATE `rolf_risks` SET `description1` = 'Que informação é armazenada nos registos?\nNome das pessoas ou categorias de pessoas?\n(Art 15.1c)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Unable to trace people accessing the personal data';

UPDATE `rolf_risks` SET `description1` = 'Que tipos de dados são tratados?\nSalvo disposição em contrário, as seguintes categorias de dados são proibidas:\n   - origem racial ou étnica,\n   - opiniões políticas,\n   - convicções religiosas ou filosóficas\n   - filiação sindical,\n   - dados genéticos e biométricos para efeitos de identificação de uma pessoa singular\n   - dados de saúde ou dados\n   - Dados relativos à vida sexual ou à orientação sexual de uma pessoa singular\noutros casos: DCP relativos a condenações penais e infrações\n(Art. 9) (Art. 10)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Underestimated categories of data processed';

UPDATE `rolf_risks` SET `description1` = 'O consentimento é:\n  - Explícito?\n  - Positivo?\n  - Livre?\n  - Específico ao tratamento ou ao contrato?\n  - Claramente distinto dos outros elementos (do contrato)?\n(Art 7.2, 7.4)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Unfair collection of the data subject''s consent';

UPDATE `rolf_risks` SET `description1` = 'Quem é o responsável pelo tratamento?\nQual é a sua função? As suas responsabilidades?\nTem poderes para fazer cumprir todas as suas obrigações?\n(Art. 5.2)', `description3` = NULL, `description4` = NULL WHERE `label2` = 'Unidentified controller or undefined role and responsibility';
